# -*- coding: utf-8 -*-
"""Cópia de Aula prática.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JulGGiiQVoPuwWize5L0ftuYNNxJdtN2

## **Introdução ao Machine Learning - Aula Prática**
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

iris = load_iris()
X = iris['data']
y = iris['target']

"""## Explorando Dados 
Descrevendo os dados do data set Iris
"""

print("\nCampos to dataset Iris ({0}):\n{1}\n".format("iris.keys()", iris.keys()))
print("\nParte da descrição do dataset Iris ({0}):\n{1}\n".format("iris['DESCR'][:471]", iris['DESCR'][:471]))
print("\nNomes das classes ({0}):\n{1}\n".format("iris['iris[target_names']",iris['target_names']))
print("\nNomes das features ({0}):\n{1}\n".format("iris['feature_names']",iris['feature_names']))



"""# DIVISÃO DAS BASES: BASE DE  TESTE E BASE DE TREINAMENTO"""

X_train, X_test, y_train, y_test = train_test_split(iris['data'], iris['target'], random_state=0)
print("\nBase de teste ({0}):\n{1}\n".format("X_train.shape", X_train.shape))
print("\nBase de teste ({0}):\n{1}\n".format("X_test.shape", X_test.shape))

"""## Visualização de dados"""

iris_dataframe = pd.DataFrame(np.c_[iris['data'], iris['target']], columns=np.append(iris['feature_names'], 'target'))
ax2 = pd.plotting.scatter_matrix(iris_dataframe.iloc[:,:5], figsize=(11,11), c=y, marker='0', hist_kwds={'bins': 20}, s=60, alpha=.8)
plt.figure()
ax3 = pd.plotting.parallel_coordinates(iris_dataframe, "target")